// <auto-generated />
namespace HowItShouldBeDone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_GenreId_ArtistId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_GenreId_ArtistId));
        
        string IMigrationMetadata.Id
        {
            get { return "202206151544058_Added_GenreId_ArtistId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
